export const CAUSES = [
    "possessed by a cursed VHS tape",
    "dragged into the underworld by shadowy hands",
    "devoured by a swarm of demonic crows",
    "drowned in a bathtub filled with black goo",
    "vanished after answering a phone call from beyond",
    "turned into a porcelain doll during a blood moon",
    "claimed by a faceless entity lurking under the bed",
    "locked inside a mirror dimension forever",
    "fell victim to an ancient forest ritual gone wrong",
    "whispered to death by unseen voices",
    "stalked and consumed by the thing in the walls",
    "melted slowly under a cursed candlelight",
    "absorbed into a haunted painting",
    "driven mad by the Reaper's lullaby",
    "sacrificed in a forgotten cult's midnight ceremony",
    "encased alive inside an abandoned well",
    "trapped in an endless loop of their own worst nightmare",
    "spirited away by a carriage with no horses",
    "cut by scissors that moved on their own",
    "claimed by the fog on a moonless night",
    "choked on a piece of food while alone at home",
    "hit by a car crossing the street on a rainy night",
    "slipped and fell down the stairs in the dark",
    "struck by lightning during a summer storm",
    "stuck in an elevator during a power outage",
    "suffocated by a pillow in their sleep",
    "fell from a great height while taking a photo",
    "strangled during a home invasion",
    "succumbed to a heart attack while running",
    "died in a fire after falling asleep with a lit cigarette",
    "killed in a car crash while texting and driving",
    "poisoned by contaminated food at a restaurant",
    "drowned while swimming in the ocean at night",
    "murdered in their sleep by a stalker",
    "collapsed from exhaustion during a marathon",
    "accidentally shot by a hunting rifle",
    "fell through the ice while walking on a frozen lake",
    "struck by falling debris in a construction zone",
    "killed by a falling tree while hiking",
    "found dead after a sudden and unexplained illness",
];


export const MESSAGES = {
    missingData: "Please enter your full name and birthdate to discover your fate!",
    invalidName: "Please enter your full name.",
    invalidAge: "The Reaper knows no one of this age... Please enter a valid birthdate.",
    resultIntro: (name) => `${name}, your fate has been sealed.`,
    resultFull: (name, date, cause) =>
        `${name}, your fate has been sealed. Date of death: ${date}. Cause: ${cause}.`,
};

export const SETTINGS = {
    maxAge: 90,
    minNameWords: 2,
    bgMusicVolume: 0.02,
    laughVolume: 0.3,
    speech: {
        pitch: 0,
        rate: 0.8,
        volume: 1,
    },
};